"""
LinkedIn Poster for AI Employee

This module handles automatic LinkedIn post generation and posting.
"""
import time
import logging
from pathlib import Path
from datetime import datetime
import sys
import os
import requests
from config_loader import get_env_variable

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class LinkedInPoster:
    """Handles LinkedIn posting functionality"""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / "Needs_Action"
        self.posts_dir = self.vault_path / "LinkedIn_Posts"
        self.posts_dir.mkdir(exist_ok=True)

    def generate_business_update(self, topic: str = "general") -> str:
        """Generate a business update post based on the topic"""
        posts = {
            "general": f""" excited to share that we're making great progress in our projects this week!

Our team has been working hard on delivering value to our clients and innovating in our field.

#BusinessUpdate #Innovation #TeamWork""",
            "achievement": f""" thrilled to announce a significant milestone in one of our key projects!

This achievement reflects our team's dedication and expertise. Looking forward to what's next!

#Achievement #Milestone #TeamWork""",
            "insight": f""" been reflecting on industry trends and wanted to share some insights:

The future of our field is being shaped by innovation, collaboration, and continuous learning. Excited about the opportunities ahead.

What are your thoughts on these trends?

#IndustryInsights #Innovation #Future"""
        }

        return posts.get(topic, posts["general"])

    def create_post_draft(self, content: str = None, topic: str = "general") -> Path:
        """Create a LinkedIn post draft in the vault"""
        if not content:
            content = self.generate_business_update(topic)

        post_filename = f"LINKEDIN_POST_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        post_path = self.posts_dir / post_filename

        post_content = f"""---
type: linkedin_post
status: draft
created: {datetime.now().isoformat()}
scheduled: {datetime.now().replace(hour=12, minute=0, second=0, microsecond=0).isoformat()}
topic: {topic}
---

# LinkedIn Post Draft

## Content
{content}

## Suggested Actions
- [ ] Review content
- [ ] Approve for posting
- [ ] Schedule optimal posting time
- [ ] Monitor engagement after posting

## Notes
This post was automatically generated by the AI Employee.
"""
        post_path.write_text(post_content)
        logger.info(f"Created LinkedIn post draft: {post_path.name}")
        return post_path

    def schedule_post(self, post_file: Path, scheduled_time: datetime = None) -> bool:
        """Schedule a post for later publishing"""
        if not scheduled_time:
            # Default to next business day at 12 PM
            scheduled_time = datetime.now().replace(hour=12, minute=0, second=0, microsecond=0)

        # Update the post file with scheduled time
        content = post_file.read_text()
        updated_content = content.replace(
            'scheduled: null',
            f'scheduled: {scheduled_time.isoformat()}'
        )
        post_file.write_text(updated_content)

        logger.info(f"Scheduled post {post_file.name} for {scheduled_time}")
        return True

    def post_now(self, content: str) -> dict:
        """
        Post content to LinkedIn using the LinkedIn API.
        """
        logger.info(f"Posting to LinkedIn: {content[:50]}...")

        # Get LinkedIn API credentials from environment variables
        linkedin_access_token = get_env_variable('LINKEDIN_ACCESS_TOKEN')
        linkedin_api_key = get_env_variable('LINKEDIN_API_KEY')

        if not linkedin_access_token:
            # If no access token is provided, we can't make a real API call
            logger.warning("LINKEDIN_ACCESS_TOKEN not found. Cannot post to LinkedIn API.")
            logger.info("Creating post draft instead.")
            post_path = self.create_post_draft(content=content)
            return {
                "success": False,
                "message": "LINKEDIN_ACCESS_TOKEN not configured. Created draft only.",
                "draft_path": str(post_path),
                "timestamp": datetime.now().isoformat()
            }

        try:
            # LinkedIn API endpoint for creating posts
            api_url = "https://api.linkedin.com/v2/ugcPosts"

            # First, we need to get the author's URN (user ID)
            # Usually this is in the format: urn:li:person:<person_id>
            # For now, we'll assume the user has provided their URN or we'll use the access token to get it
            author_urn = self.get_author_urn(linkedin_access_token)

            if not author_urn:
                # If we can't get the author URN, create a draft
                logger.warning("Could not determine LinkedIn author URN. Creating draft only.")
                post_path = self.create_post_draft(content=content)
                return {
                    "success": False,
                    "message": "Could not determine LinkedIn author URN. Created draft only.",
                    "draft_path": str(post_path),
                    "timestamp": datetime.now().isoformat()
                }

            # Prepare the post payload
            headers = {
                "Authorization": f"Bearer {linkedin_access_token}",
                "Content-Type": "application/json",
                "X-Restli-Protocol-Version": "2.0.0"
            }

            post_payload = {
                "author": author_urn,
                "lifecycleState": "PUBLISHED",
                "specificContent": {
                    "com.linkedin.ugc.ShareContent": {
                        "shareCommentary": {
                            "text": content
                        },
                        "shareMediaCategory": "NONE"
                    }
                },
                "visibility": {
                    "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
                }
            }

            # Make the API call to LinkedIn
            response = requests.post(api_url, headers=headers, json=post_payload)

            if response.status_code in [200, 201]:
                # Success
                response_data = response.json()
                post_id = response_data.get('id', f"post_{int(time.time())}")

                logger.info(f"Successfully posted to LinkedIn. Post ID: {post_id}")

                # Also save it as a draft for record keeping
                post_path = self.create_post_draft(content=content)

                return {
                    "success": True,
                    "post_id": post_id,
                    "message": "Post published successfully to LinkedIn",
                    "timestamp": datetime.now().isoformat(),
                    "draft_path": str(post_path)
                }
            else:
                logger.error(f"Failed to post to LinkedIn. Status: {response.status_code}, Response: {response.text}")

                # Create a draft for manual posting
                post_path = self.create_post_draft(content=content)

                return {
                    "success": False,
                    "message": f"Failed to post to LinkedIn: {response.status_code}",
                    "error_details": response.text,
                    "draft_path": str(post_path),
                    "timestamp": datetime.now().isoformat()
                }

        except Exception as e:
            logger.error(f"Error posting to LinkedIn: {str(e)}")

            # Create a draft for manual posting
            post_path = self.create_post_draft(content=content)

            return {
                "success": False,
                "message": f"Error posting to LinkedIn: {str(e)}",
                "draft_path": str(post_path),
                "timestamp": datetime.now().isoformat()
            }

    def get_author_urn(self, access_token: str) -> str:
        """
        Get the author URN (user ID) from LinkedIn API using the access token.
        First check if the user has specified the URN directly in environment variables,
        otherwise try to fetch it from the API.
        """
        # First, check if the user has provided the URN directly in environment variables
        linkedin_urn = get_env_variable('LINKEDIN_PERSON_URN')
        if linkedin_urn:
            logger.info(f"Using provided LinkedIn URN: {linkedin_urn}")
            return linkedin_urn

        try:
            headers = {
                "Authorization": f"Bearer {access_token}",
                "X-Restli-Protocol-Version": "2.0.0"
            }

            # Get the user's profile information
            profile_url = "https://api.linkedin.com/v2/me"
            response = requests.get(profile_url, headers=headers)

            if response.status_code == 200:
                profile_data = response.json()
                person_id = profile_data.get('id')

                if person_id:
                    urn = f"urn:li:person:{person_id}"
                    logger.info(f"Retrieved LinkedIn URN: {urn}")
                    # Optionally store this in environment for future use
                    return urn
                else:
                    logger.warning("Could not get person ID from LinkedIn profile")
                    return None
            else:
                logger.warning(f"Could not get LinkedIn profile: {response.status_code}, {response.text}")
                return None

        except Exception as e:
            logger.warning(f"Error getting LinkedIn profile: {str(e)}")
            return None

def main():
    """Main function to demonstrate LinkedIn posting capability"""
    vault_path = Path("../AI_Employee_Vault")

    # Create vault structure if needed
    (vault_path / "Needs_Action").mkdir(exist_ok=True)

    poster = LinkedInPoster(str(vault_path))

    # Generate and create a sample post
    post_path = poster.create_post_draft(topic="achievement")

    logger.info("LinkedIn posting capability demo completed")
    logger.info(f"Created post draft at: {post_path}")

if __name__ == "__main__":
    main()