"""
File Processing Agent Skill for AI Employee

This skill handles file operations for the AI Employee.
"""
import json
from typing import Dict, Any, List
from pathlib import Path
from datetime import datetime

def create_action_file(content: str, file_type: str = "general", priority: str = "medium") -> Dict[str, Any]:
    """
    Create an action file in the Needs_Action folder.

    Args:
        content: Content for the action file
        file_type: Type of action (email, document, task, etc.)
        priority: Priority level (low, medium, high)

    Returns:
        Dictionary with success status and file path
    """
    vault_path = Path("../AI_Employee_Vault")
    needs_action_path = vault_path / "Needs_Action"
    needs_action_path.mkdir(exist_ok=True)

    # Create the action file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    action_filename = f"SKILL_ACTION_{timestamp}_{file_type.upper()}.md"
    action_file_path = needs_action_path / action_filename

    action_content = f"""---
type: {file_type}
priority: {priority}
status: pending
created: {datetime.now().isoformat()}
source: agent_skill
---

# AI Employee Action Request

## Content
{content}

## Processing Instructions
- [ ] Review request
- [ ] Determine appropriate action
- [ ] Execute action
- [ ] Move to Done

## Suggested Actions
- [ ] Process as needed
- [ ] Create follow-up tasks if necessary
- [ ] Update relevant records

## Notes
This action was created by the AI Employee using file processing skill.
"""

    action_file_path.write_text(action_content)

    return {
        "success": True,
        "file_path": str(action_file_path),
        "message": f"Action file created: {action_filename}"
    }

def create_plan_file(objective: str, tasks: List[str], timeline: str = "TBD") -> Dict[str, Any]:
    """
    Create a Plan.md file with specified objective and tasks.

    Args:
        objective: The main objective of the plan
        tasks: List of tasks to complete
        timeline: Timeline for completion

    Returns:
        Dictionary with success status and plan file path
    """
    vault_path = Path("../AI_Employee_Vault")
    plans_path = vault_path / "Plans"
    plans_path.mkdir(exist_ok=True)

    # Create the plan file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    plan_filename = f"PLAN_SKILL_{timestamp}.md"
    plan_file_path = plans_path / plan_filename

    # Format tasks as checklist
    task_list = ""
    for i, task in enumerate(tasks):
        task_list += f"- [ ] {task}\n"

    plan_content = f"""---
created: {datetime.now().isoformat()}
status: pending_approval
timeline: {timeline}
---

# AI Employee Action Plan

## Objective
{objective}

## Tasks to Complete
{task_list}

## Approval Required
- [ ] Human review and approval of this plan

## Timeline
- Started: {datetime.now().isoformat()}
- Estimated completion: {timeline}
- Required by: [TBD]

## Success Criteria
- [ ] Objective achieved
- [ ] All tasks completed
- [ ] Status updated in system

## Notes
This plan was automatically generated by the AI Employee using the file processing skill.
"""

    plan_file_path.write_text(plan_content)

    return {
        "success": True,
        "file_path": str(plan_file_path),
        "message": f"Plan file created: {plan_filename}"
    }

def check_pending_actions(folder: str = "Needs_Action") -> List[Dict[str, Any]]:
    """
    Check for pending actions in specified folder.

    Args:
        folder: Folder to check (Needs_Action, Pending_Approval, etc.)

    Returns:
        List of pending action files
    """
    vault_path = Path("../AI_Employee_Vault")
    target_path = vault_path / folder
    target_path.mkdir(exist_ok=True)

    pending_files = []
    for file_path in target_path.glob("*.md"):
        # Read the first few lines to get basic info
        with open(file_path, 'r', encoding='utf-8') as f:
            first_lines = f.read(200)  # Read first 200 characters

        pending_files.append({
            "filename": file_path.name,
            "path": str(file_path),
            "size": file_path.stat().st_size,
            "preview": first_lines
        })

    return pending_files

def move_file(source_folder: str, target_folder: str, filename: str) -> Dict[str, Any]:
    """
    Move a file from source folder to target folder.

    Args:
        source_folder: Source folder name
        target_folder: Target folder name
        filename: Name of the file to move

    Returns:
        Dictionary with success status
    """
    vault_path = Path("../AI_Employee_Vault")
    source_path = vault_path / source_folder
    target_path = vault_path / target_folder

    # Create target folder if it doesn't exist
    target_path.mkdir(parents=True, exist_ok=True)

    source_file = source_path / filename
    target_file = target_path / filename

    if not source_file.exists():
        return {
            "success": False,
            "message": f"Source file does not exist: {source_file}"
        }

    try:
        source_file.rename(target_file)
        return {
            "success": True,
            "message": f"File moved from {source_folder} to {target_folder}: {filename}"
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error moving file: {str(e)}"
        }

# Define the skill specification
SKILL_SPEC = {
    "name": "file_processing_skill",
    "description": "Handles file operations for the AI Employee",
    "functions": [
        {
            "name": "create_action_file",
            "description": "Create an action file in the Needs_Action folder",
            "parameters": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Content for the action file"},
                    "file_type": {"type": "string", "description": "Type of action: email, document, task, etc. (default: general)"},
                    "priority": {"type": "string", "description": "Priority level: low, medium, high (default: medium)"}
                },
                "required": ["content"]
            }
        },
        {
            "name": "create_plan_file",
            "description": "Create a Plan.md file with objective and tasks",
            "parameters": {
                "type": "object",
                "properties": {
                    "objective": {"type": "string", "description": "The main objective of the plan"},
                    "tasks": {"type": "array", "items": {"type": "string"}, "description": "List of tasks to complete"},
                    "timeline": {"type": "string", "description": "Timeline for completion (optional)"}
                },
                "required": ["objective", "tasks"]
            }
        },
        {
            "name": "check_pending_actions",
            "description": "Check for pending actions in specified folder",
            "parameters": {
                "type": "object",
                "properties": {
                    "folder": {"type": "string", "description": "Folder to check (default: Needs_Action)"}
                }
            }
        },
        {
            "name": "move_file",
            "description": "Move a file from source folder to target folder",
            "parameters": {
                "type": "object",
                "properties": {
                    "source_folder": {"type": "string", "description": "Source folder name"},
                    "target_folder": {"type": "string", "description": "Target folder name"},
                    "filename": {"type": "string", "description": "Name of the file to move"}
                },
                "required": ["source_folder", "target_folder", "filename"]
            }
        }
    ]
}