"""
Social Media Agent Skill for AI Employee

This skill handles social media operations including LinkedIn posting.
"""
import json
from typing import Dict, Any, List
from pathlib import Path
from datetime import datetime, timedelta

def create_linkedin_post(content: str, visibility: str = "public") -> Dict[str, Any]:
    """
    Create a LinkedIn post draft.

    Args:
        content: Content for the LinkedIn post
        visibility: Post visibility (public, connections-only)

    Returns:
        Dictionary with success status and post information
    """
    vault_path = Path("../AI_Employee_Vault")
    linkedin_posts_path = vault_path / "LinkedIn_Posts"
    linkedin_posts_path.mkdir(parents=True, exist_ok=True)

    # Create the post file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    post_filename = f"LINKEDIN_POST_{timestamp}.md"
    post_file_path = linkedin_posts_path / post_filename

    post_content = f"""---
type: linkedin_post
visibility: {visibility}
status: draft
created: {datetime.now().isoformat()}
scheduled: {datetime.now().replace(hour=12, minute=0, second=0, microsecond=0).isoformat()}
---

# LinkedIn Post Draft

## Content
{content}

## Suggested Actions
- [ ] Review content
- [ ] Approve for posting
- [ ] Schedule optimal posting time
- [ ] Monitor engagement after posting

## Notes
This post was automatically generated by the AI Employee using social media skill.
"""
    post_file_path.write_text(post_content)

    return {
        "success": True,
        "file_path": str(post_file_path),
        "message": f"LinkedIn post draft created: {post_filename}"
    }

def schedule_linkedin_post(post_file_path: str, scheduled_time: str = None) -> Dict[str, Any]:
    """
    Schedule a LinkedIn post for later publishing.

    Args:
        post_file_path: Path to the post file to schedule
        scheduled_time: Scheduled time in ISO format (defaults to next business day at 12 PM)

    Returns:
        Dictionary with success status
    """
    if not scheduled_time:
        # Default to next business day at 12 PM
        scheduled_time = (datetime.now() + timedelta(days=1)).replace(hour=12, minute=0, second=0, microsecond=0).isoformat()

    # Update the post file with scheduled time
    post_path = Path(post_file_path)
    if not post_path.exists():
        return {
            "success": False,
            "message": f"Post file does not exist: {post_file_path}"
        }

    content = post_path.read_text()
    # Replace the scheduled time in the YAML front matter
    import re
    updated_content = re.sub(
        r'scheduled:.*',
        f'scheduled: {scheduled_time}',
        content,
        count=1
    )
    post_path.write_text(updated_content)

    return {
        "success": True,
        "message": f"Post scheduled for: {scheduled_time}"
    }

def generate_business_update(update_type: str = "general") -> str:
    """
    Generate a business update post based on type.

    Args:
        update_type: Type of business update (general, achievement, insight, news)

    Returns:
        Generated LinkedIn post content
    """
    updates = {
        "general": f""" excited to share that we're making great progress in our projects this week!

Our team has been working hard on delivering value to our clients and innovating in our field.

#BusinessUpdate #Innovation #TeamWork""",
        "achievement": f""" thrilled to announce a significant milestone in one of our key projects!

This achievement reflects our team's dedication and expertise. Looking forward to what's next!

#Achievement #Milestone #TeamWork""",
        "insight": f""" been reflecting on industry trends and wanted to share some insights:

The future of our field is being shaped by innovation, collaboration, and continuous learning. Excited about the opportunities ahead.

What are your thoughts on these trends?

#IndustryInsights #Innovation #Future""",
        "news": f""" excited to share some exciting developments from our latest project!

We've been exploring new approaches to deliver even better results for our clients. The future looks bright!

#Innovation #Progress #Excellence"""
    }

    return updates.get(update_type, updates["general"])

def create_post_from_content(content: str, hashtags: List[str] = None) -> Dict[str, Any]:
    """
    Create a LinkedIn post from provided content with optional hashtags.

    Args:
        content: Main content for the post
        hashtags: List of hashtags to include

    Returns:
        Dictionary with success status and post information
    """
    if hashtags:
        hashtag_str = " ".join([f"#{tag.strip('#')}" for tag in hashtags])
        full_content = f"{content}\n\n{hashtag_str}"
    else:
        full_content = content

    return create_linkedin_post(full_content)

def get_scheduled_posts() -> List[Dict[str, Any]]:
    """
    Get all scheduled LinkedIn posts.

    Returns:
        List of scheduled posts
    """
    vault_path = Path("../AI_Employee_Vault")
    linkedin_posts_path = vault_path / "LinkedIn_Posts"

    if not linkedin_posts_path.exists():
        return []

    scheduled_posts = []
    for post_file in linkedin_posts_path.glob("*.md"):
        content = post_file.read_text()

        # Extract scheduled information from front matter
        import re
        scheduled_match = re.search(r'scheduled:\s*(.*)', content)
        status_match = re.search(r'status:\s*(.*)', content)

        if scheduled_match:
            scheduled_time = scheduled_match.group(1).strip()
            status = status_match.group(1).strip() if status_match else "unknown"

            scheduled_posts.append({
                "filename": post_file.name,
                "path": str(post_file),
                "scheduled_time": scheduled_time,
                "status": status
            })

    return scheduled_posts

# Define the skill specification
SKILL_SPEC = {
    "name": "social_media_skill",
    "description": "Handles social media operations including LinkedIn posting",
    "functions": [
        {
            "name": "create_linkedin_post",
            "description": "Create a LinkedIn post draft",
            "parameters": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Content for the LinkedIn post"},
                    "visibility": {"type": "string", "description": "Post visibility: public, connections-only (default: public)"}
                },
                "required": ["content"]
            }
        },
        {
            "name": "schedule_linkedin_post",
            "description": "Schedule a LinkedIn post for later publishing",
            "parameters": {
                "type": "object",
                "properties": {
                    "post_file_path": {"type": "string", "description": "Path to the post file to schedule"},
                    "scheduled_time": {"type": "string", "description": "Scheduled time in ISO format (optional, defaults to next business day)"}
                },
                "required": ["post_file_path"]
            }
        },
        {
            "name": "generate_business_update",
            "description": "Generate a business update post based on type",
            "parameters": {
                "type": "object",
                "properties": {
                    "update_type": {"type": "string", "description": "Type of business update: general, achievement, insight, news (default: general)"}
                }
            }
        },
        {
            "name": "create_post_from_content",
            "description": "Create a LinkedIn post from provided content with optional hashtags",
            "parameters": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Main content for the post"},
                    "hashtags": {"type": "array", "items": {"type": "string"}, "description": "List of hashtags to include"}
                },
                "required": ["content"]
            }
        },
        {
            "name": "get_scheduled_posts",
            "description": "Get all scheduled LinkedIn posts",
            "parameters": {
                "type": "object",
                "properties": {}
            }
        }
    ]
}