"""
Social Media Integration for AI Employee

This module handles Facebook and Instagram integration for the Gold Tier.
Includes human-in-the-loop approval workflow before publishing.
"""
import time
import logging
from pathlib import Path
from datetime import datetime
import json
import sys
import os

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class SocialMediaIntegrator:
    """Handles Facebook and Instagram integration with approval workflow"""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / "Needs_Action"
        self.social_posts = self.vault_path / "Social_Posts"
        self.pending_approval_dir = self.vault_path / "Plans" / "Pending_Approval" / "Social_Media"
        self.social_posts.mkdir(exist_ok=True)
        self.pending_approval_dir.mkdir(parents=True, exist_ok=True)

    def create_facebook_post(self, content: str, image_path: str = None, schedule_time: str = None) -> dict:
        """
        Create a Facebook post draft (simulated for this implementation).

        Args:
            content: Post content
            image_path: Path to image (optional)
            schedule_time: Schedule time in ISO format (optional)

        Returns:
            Dictionary with success status and post information
        """
        logger.info(f"Creating Facebook post: {content[:50]}...")

        post_filename = f"FB_POST_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        post_path = self.social_posts / post_filename

        post_content = f"""---
type: facebook_post
status: draft
created: {datetime.now().isoformat()}
scheduled: {schedule_time or datetime.now().isoformat()}
platform: facebook
---

# Facebook Post Draft

## Content
{content}

## Attachments
- Image: {image_path or 'None'}

## Suggested Actions
- [ ] Review content
- [ ] Approve for posting
- [ ] Schedule posting time
- [ ] Monitor engagement after posting

## Notes
This post was automatically generated by the AI Employee for Facebook.
"""
        post_path.write_text(post_content, encoding='utf-8')

        return {
            "success": True,
            "post_id": post_filename,
            "message": f"Facebook post draft created: {post_filename}"
        }

    def create_instagram_post(self, content: str, image_path: str, caption: str = None) -> dict:
        """
        Create an Instagram post draft (simulated for this implementation).

        Args:
            content: Post content/caption
            image_path: Path to image
            caption: Alternative caption (optional, defaults to content)

        Returns:
            Dictionary with success status and post information
        """
        logger.info(f"Creating Instagram post: {content[:50]}...")

        post_filename = f"IG_POST_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        post_path = self.social_posts / post_filename

        if not caption:
            caption = content

        post_content = f"""---
type: instagram_post
status: draft
created: {datetime.now().isoformat()}
scheduled: {datetime.now().isoformat()}
platform: instagram
image_path: {image_path}
---

# Instagram Post Draft

## Caption
{caption}

## Image
{image_path}

## Suggested Actions
- [ ] Review image and caption
- [ ] Approve for posting
- [ ] Schedule optimal posting time
- [ ] Monitor engagement after posting

## Notes
This post was automatically generated by the AI Employee for Instagram.
"""
        post_path.write_text(post_content, encoding='utf-8')

        return {
            "success": True,
            "post_id": post_filename,
            "message": f"Instagram post draft created: {post_filename}"
        }

    def schedule_social_post(self, post_file: Path, platform: str, schedule_time: str) -> dict:
        """
        Schedule a social media post for later publishing.

        Args:
            post_file: Path to the post file
            platform: Target platform ('facebook', 'instagram', 'twitter')
            schedule_time: Schedule time in ISO format

        Returns:
            Dictionary with success status
        """
        logger.info(f"Scheduling {platform} post: {post_file.name}")

        # Update the post file with scheduling information
        content = post_file.read_text()
        updated_content = content.replace(
            'scheduled: null',
            f'scheduled: {schedule_time}'
        ).replace(
            'status: draft',
            'status: scheduled'
        )

        post_file.write_text(updated_content)

        return {
            "success": True,
            "message": f"Post scheduled for {schedule_time} on {platform}"
        }

    def generate_cross_platform_content(self, topic: str, include_images: bool = True) -> dict:
        """
        Generate content suitable for multiple social platforms.

        Args:
            topic: Main topic/theme
            include_images: Whether to suggest images

        Returns:
            Dictionary with content for different platforms
        """
        content_variants = {
            "facebook": f""" excited to share insights about {topic}!

We've been exploring new approaches to deliver better results in this area. The possibilities are exciting!

What are your thoughts on {topic}?

#BusinessInsights #{topic.replace(' ', '')}""",
            "instagram": f"""Exploring new possibilities in {topic}!

The future is bright when innovation meets dedication. 🚀

#Business #{topic.replace(' ', '')} #Innovation""",
            "twitter": f"""Exploring {topic} - the future of our industry is being shaped by innovation, collaboration, and continuous learning. Excited about the opportunities ahead! #{topic.replace(' ', '')} #Innovation"""
        }

        # Create posts for all platforms
        created_posts = {}
        for platform, content in content_variants.items():
            if platform == "facebook":
                result = self.create_facebook_post(content)
            elif platform == "instagram":
                # For Instagram, we need an image path, but we'll simulate it
                result = self.create_instagram_post(content, f"images/{topic.replace(' ', '_').lower()}_image.jpg")
            else:  # Twitter would be handled separately
                # Create a generic post for other platforms
                post_filename = f"{platform.upper()}_POST_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
                post_path = self.social_posts / post_filename
                post_content = f"""---
type: {platform}_post
status: draft
created: {datetime.now().isoformat()}
platform: {platform}
---

# {platform.title()} Post Draft

## Content
{content}

## Suggested Actions
- [ ] Review content
- [ ] Approve for posting
- [ ] Schedule posting time
- [ ] Monitor engagement

## Notes
This post was automatically generated by the AI Employee for {platform}.
"""
                post_path.write_text(post_content, encoding='utf-8')
                result = {
                    "success": True,
                    "post_id": post_filename,
                    "message": f"{platform.title()} post draft created: {post_filename}"
                }

            created_posts[platform] = result

        return created_posts

    def generate_summary_report(self) -> dict:
        """
        Generate a summary report of social media activities.

        Returns:
            Dictionary with summary statistics
        """
        # Count draft posts
        draft_posts = list(self.social_posts.glob("*_POST_*.md"))
        draft_count = len(draft_posts)

        # Count by platform
        fb_posts = [p for p in draft_posts if p.name.startswith('FB_')]
        ig_posts = [p for p in draft_posts if p.name.startswith('IG_')]
        other_posts = [p for p in draft_posts if not p.name.startswith(('FB_', 'IG_'))]

        summary = {
            "generated_at": datetime.now().isoformat(),
            "total_drafts": draft_count,
            "facebook_drafts": len(fb_posts),
            "instagram_drafts": len(ig_posts),
            "other_platforms_drafts": len(other_posts),
            "latest_posts": [p.name for p in draft_posts[-5:]]  # Last 5 posts
        }

        # Create a summary file
        summary_filename = f"Social_Media_Summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        summary_path = self.social_posts / summary_filename

        summary_content = f"""---
type: social_media_summary
created: {datetime.now().isoformat()}
---

# Social Media Activity Summary

## Statistics
- Total draft posts: {summary['total_drafts']}
- Facebook drafts: {summary['facebook_drafts']}
- Instagram drafts: {summary['instagram_drafts']}
- Other platform drafts: {summary['other_platforms_drafts']}

## Latest Posts
{chr(10).join([f"- {post}" for post in summary['latest_posts']])}

## Generated
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Notes
This summary was automatically generated by the AI Employee.
"""
        summary_path.write_text(summary_content)

        return summary

    def submit_post_for_approval(self, post_file: Path, reason: str = "Social media post for business growth") -> Path:
        """
        Submit a draft post for human approval before publishing.
        
        Args:
            post_file: Path to the draft post file
            reason: Reason/business justification for this post
            
        Returns:
            Path to the approval request file
        """
        if not post_file.exists():
            logger.error(f"Post file does not exist: {post_file}")
            return None
        
        # Read the post content
        content = post_file.read_text()
        
        # Extract platform from frontmatter
        platform = 'unknown'
        for line in content.split('\n'):
            if line.startswith('platform:'):
                platform = line.split(':', 1)[1].strip()
                break
        
        # Extract post content
        post_text = self._extract_post_content(content)
        
        # Create approval request
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        approval_filename = f"SOCIAL_APPROVAL_{platform.upper()}_{timestamp}.md"
        approval_path = self.pending_approval_dir / approval_filename
        
        approval_content = f"""---
type: social_media_approval
platform: {platform}
status: pending
created: {datetime.now().isoformat()}
source_file: {str(post_file)}
reason: {reason}
---

# Social Media Approval Request

## Platform
**{platform.upper()}**

## Post Content
```
{post_text}
```

## Details
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Platform:** {platform.upper()}
- **Reason:** {reason}
- **Source File:** `{post_file.name}`

## Instructions

### ✅ To Approve:
1. Review the post content above
2. Move this file to: `Plans/Approved/Social_Media/`
3. The post will be automatically published

### ❌ To Reject:
1. Move this file to: `Plans/Rejected/Social_Media/`
2. Add a comment explaining why (optional)

### ✏️ To Modify:
1. Edit the post content in the source file
2. Delete this approval request
3. Re-submit for approval

---
*Generated by AI Employee - Human-in-the-Loop Approval Required*
"""
        
        approval_path.write_text(approval_content, encoding='utf-8')
        logger.info(f"Created approval request: {approval_path.name}")
        
        # Update post status
        updated_content = content.replace('status: draft', 'status: pending_approval')
        post_file.write_text(updated_content, encoding='utf-8')
        
        return approval_path

    def _extract_post_content(self, markdown_content: str) -> str:
        """Extract the actual post content from markdown file"""
        lines = markdown_content.split('\n')
        in_content = False
        content_lines = []
        
        for line in lines:
            if line.startswith('## Content') or line.startswith('## Caption'):
                in_content = True
                continue
            elif line.startswith('## ') and in_content:
                break
            elif in_content and not line.startswith('---'):
                content_lines.append(line)
        
        return '\n'.join(content_lines).strip() if content_lines else "Content not found"

def main():
    """Main function to demonstrate social media integration with approval workflow"""
    vault_path = Path("../AI_Employee_Vault")

    # Create vault structure if needed
    (vault_path / "Needs_Action").mkdir(exist_ok=True)

    integrator = SocialMediaIntegrator(str(vault_path))

    print("=== Social Media Integration with Approval Workflow ===\n")

    # Create sample posts
    print("Creating Facebook post...")
    fb_post = integrator.create_facebook_post(
        "🚀 Excited to announce our latest project milestone! Our team has been working hard to deliver exceptional results. #Innovation #Business",
        "images/project_milestone.jpg"
    )
    print(f"Facebook draft created: {fb_post['post_id']}")

    print("\nCreating Instagram post...")
    ig_post = integrator.create_instagram_post(
        "New project milestone achieved! Innovation at its finest.",
        "images/milestone_visual.jpg",
        "Celebrating our latest project milestone! 🎉"
    )
    print(f"Instagram draft created: {ig_post['post_id']}")

    # Submit for approval
    print("\n=== Submitting Posts for Human Approval ===")
    
    fb_post_file = vault_path / "Social_Posts" / fb_post['post_id']
    ig_post_file = vault_path / "Social_Posts" / ig_post['post_id']
    
    fb_approval = integrator.submit_post_for_approval(
        fb_post_file,
        reason="Business update to generate client interest and sales"
    )
    print(f"Facebook approval request: {fb_approval.name if fb_approval else 'Failed'}")
    
    ig_approval = integrator.submit_post_for_approval(
        ig_post_file,
        reason="Instagram engagement post for brand visibility"
    )
    print(f"Instagram approval request: {ig_approval.name if ig_approval else 'Failed'}")

    # Generate summary
    print("\nGenerating summary report...")
    summary = integrator.generate_summary_report()
    print(f"Total drafts: {summary['total_drafts']}")

    print("\n=== Workflow Status ===")
    print("[OK] Drafts created in Social_Posts/")
    print("[OK] Approval requests created in Plans/Pending_Approval/Social_Media/")
    print("[WAITING] Waiting for human approval...")
    print("[NEXT] After approval: Move to Plans/Approved/Social_Media/")
    print("[AUTO] Auto-publish will execute for approved posts")

    print("\n=== Demo Complete ===")

if __name__ == "__main__":
    main()